### ISSUE TITLE
website displaying unexpected black color

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [drHyperion451/does-uBO-bypass-yt#10]
**Describe the bug**
The website displays a black color instead of the expected green or red color. This issue was observed across Opera, Chrome, and Microsoft Edge browsers.

**To Reproduce**
1. Open the website on any of the mentioned browsers.

**Expected behavior**
I expected it to show a "Green" or "Red" colour.

**Screenshots**
<details>
<summary>Opera</summary>

![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/47966497/a3ed638e-865b-45e6-9773-6b3930e17c30)

</details>

<details>
<summary>Chrome</summary>

![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/47966497/61aa35d0-16ff-4d49-aabd-88c5f5237a6d)

</details>

<details>
<summary>Edge</summary>

![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/47966497/c895ab63-8959-4adf-a7ea-db26971a899f)

</details>

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] chrome, edge, opera
 - Version [e.g. 22] Opera One(version: 103.0.4928.47), Google Chrome Version 118.0.5993.118 (Official Build) (64-bit), Microsoft Edge Version 118.0.2088.76 (Official build) (64-bit)

**Comment by drHyperion451** [comment]
Hello, press right click -> inspect element and go to the console tab. Refresh the page and post the error messages that could appear (right click -> copy all mensagges). 

Try disabling any extension, specially the ones that modifies the page like adblockers. This website makes a fetch request to github and pastely, so if your adblocker or browser blocks this request that might be the issue.

**Comment by Shivangbhatnagar237** [comment]
I disabled all extensions using [Extensity](https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg) extension on Google Chrome. Even after that the issue persists.

Console output: 
```
Youtube latest code:  9e7f5697
main.js:11 
        
        
       GET https://raw.githubusercontent.com/stephenhawk8054/misc/main/yt-fix.txt net::ERR_CONNECTION_TIMED_OUT
fetchData @ main.js:11
getLastCodeUblock @ main.js:15
logCodes @ main.js:44
await in logCodes (async)
areCodesEqual @ main.js:110
(anonymous) @ main.js:156
load (async)
(anonymous) @ main.js:154
main.js:11 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at fetchData (main.js:11:26)
    at getLastCodeUblock (main.js:15:22)
    at logCodes (main.js:44:24)
```

<details>
<summary>Screenshot: (Click to view)</summary>

![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/47966497/5f380507-c249-4a23-affd-5fc258837715)
</details>

**Comment by drHyperion451** [comment]
It's very weird. Can you access [raw.githubusercontent.com](https://raw.githubusercontent.com/stephenhawk8054/misc/main/yt-fix.txt)? It is a fetch error so something is not letting you feetch anything with js

**Comment by Shivangbhatnagar237** [comment]
> It's very weird. Can you access [raw.githubusercontent.com](https://raw.githubusercontent.com/stephenhawk8054/misc/main/yt-fix.txt)? It is a fetch error so something is not letting you feetch anything with js

No, it just keeps buffering

**Comment by drHyperion451** [comment]
> No, it just keeps buffering

Try again without any VPN or proxies, maybe the ip is banned for avoiding DDoS attacks. I'm afraid I can't help you and you should contact GitHub if the problem continues

**Comment by Shivangbhatnagar237** [comment]
> > No, it just keeps buffering
> 
> Try again without any VPN or proxies, maybe the ip is banned for avoiding DDoS attacks. I'm afraid I can't help you and you should contact GitHub if the problem continues.
> 
> Edit: Your browser tries to fetch to raw.githubusercontent.com each time this website reloads to fetch the last ublock code. If you cannot normally access this website it could mean github blocked your ip

Okay, thanks. Should I close this issue?
