### ISSUE TITLE
The site reports green when ublock is not installed

### ISSUE THREAD

**Issue by Tahvok** [drHyperion451/does-uBO-bypass-yt#17]
I do **not** have ublock installed, but when I open that page, it is reporting green.
Now this is not an issue for me, but it may confuse less technical folks that might think that ublock is installed and operational when in fact it is not, and even cause them to report bugs to ublock unnecessarily.

**Comment by drHyperion451** [comment]
Hello, I think this is not the main purpose of the website and this is impossible to make right now without scanning user agent or something. It's a good suggestion but the only thing we could make is add a "what this website is not" or some stuff like that
