### ISSUE TITLE
Word missing a letter

### ISSUE THREAD

**Issue by doppm** [drHyperion451/does-uBO-bypass-yt#28]
**Describe the bug**
The word "detected" is missing a t between the two e's at the beginning

**To Reproduce**
1. Go to [website](https://drhyperion451.github.io/does-uBO-bypass-yt/)
2. Look under "What does it mean?"
3. See error

**Expected behavior**
I thought it would say "detected."

**Screenshots**
<img width="1226" alt="Screenshot 2023-11-09 145805" src="https://github.com/drHyperion451/does-uBO-bypass-yt/assets/150387584/721eb0c7-98c5-4e4e-bcec-ff16b053cae6">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Chrome ver. 119.0.6045.107, [does-uBO-bypass-yt](https://github.com/drHyperion451/does-uBO-bypass-yt) ver. 1.3.0

**Additional context**
Sorry it's just really bothering me also I'm new so I don't know if it counts as a bug I'm just trying to help out

**Comment by drHyperion451** [comment]
It's actually fixed in the dev branch. I'm gonna deploy it now.

**Comment by doppm** [comment]
Thank you !!
