### ISSUE TITLE
Add an auto-update quick fix filters button to the website.

### ISSUE THREAD

**Issue by drHyperion451** [drHyperion451/does-uBO-bypass-yt#30]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Inside this [website](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes) there is a quick, easy and idiot proof way to update only the quick fix filters, solving two big problems of the uBO vs YT event:
1. Updating the filters are not an extremely easy task to do and involves going pages inside pages etc. Too many steps to do for people who doesn't understand quite well how anti-adblocking works.
2. Purge cache & force update is a bad practice and can overload the server unnnecesary, since all youtube bypass fixes are pushed in the quick fix filters.

**Describe steps you've considered**
- Add the button in html as a "aa-blocked" class so it will be displayed only if the filters are updated.
- Make the button work. Either using a html anchor or use js. Use this url: https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes#
- Make it beauty using CSS **HELP NEEDED ON THIS**

**Supply code**
I will contribute inside the branch attached to this issue.

**Comment by iam-py-test** [comment]
Sadly, this is not possible, as I believe
> The ability to update filter lists through a specially crafted link is available only on uBO's own support sites

Thanks

**Comment by drHyperion451** [comment]
> [Sadly, this is not possible, as I believe](https://github.com/gorhill/uBlock/commit/0325dcdcb4)
> 
> > The ability to update filter lists through a specially crafted link is available only on uBO's own support sites
> 
> Thanks

At least we could redirect people into the website. We have another options if the uBO devs want to make it more quick:
1. Ask the devs to add my subdomain to their whitelist. (Unsafe but fast)
2. Transfer this repo to [ublockorigin.github.io/](https://ublockorigin.github.io/). ( I could be a colaborator but I loose  ownership)
3. Leave as is but change a bit this website: [ublockorigin.github.io/uAssets/update-lists.html](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters,easylist) So it's not ugly.

**Comment by drHyperion451** [comment]
Last but not least. I could change the location of the deployed guthub pages to an approved domain, but I need to investigate this

**Comment by gorhill** [comment]
> Leave as is but change a bit this website: [ublockorigin.github.io/uAssets/update-lists.html](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters,easylist) So it's not ugly.

I am open to pull request to improve this. Just mind that there is an alternative version presented for when a user is still on an old version of uBO (less than 1.53.0) or when the URL does not contain the needed parameters, for exmaple: <https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=>

**Comment by gwarser** [comment]
Button does not fit on the screen on HD monitor.

**Comment by drHyperion451** [comment]
> Button does not fit on the screen on HD monitor.

Add another issuee and please post screen resolution and a screenshot
