### ISSUE TITLE
Ability to change the language of the website

### ISSUE THREAD

**Issue by MrTorfick** [drHyperion451/does-uBO-bypass-yt#34]
**Is your request related to a problem? Please describe it.**
Not a problem

**Describe the solution you would like to see
By some select, or some kind of option, allow the user to select a language. Or automatically detect the browser language, and implement it.

 **Describe the alternatives you have considered** **A clear and concise description of the alternative solutions or features you have considered.**
Browser translations (which are not accurate)

**Additional context**
Add here any additional context or screenshots about the feature request.

**Code**
I could implement it, it would take me some time. I would like to know if you don't mind if I implement this functionality. In my case I would translate the site into Spanish.

**Comment by drHyperion451** [comment]
Hello. I was thinking about that lately (since I'm not a native english speaker). However, I have no clue on how to implement this due to lack of experience on web development. Maybe we could set multiple html files inside a lang folder and then redirect them or another better solution that is not horrible for maintaining this in the future.

**Comment by drHyperion451** [comment]
> redirect to another page like spanish.html

This is a good option, but this is very panful if you want to support more than one language and want to maintain the project. Any change or addition we apply on the english html should be changed in all languages too.

I was thinking on two options actually:
1. Leave the index.html and add ids to each piece of information. Create a json for each language and add the translations there.
2. Remove the banner completely inside the index.html and generate this using javascript on the execution time.

I view the second one overcomplicated.

I'm very busy right now irl, so maybe this project wiill have less frequent updates

**Comment by drHyperion451** [comment]
@MrTorfick Lets make something provisional for now.

Copy the index.html file to lang/spanish.html and make the translations you want there. The spanish version will be in this route for now until I create something better.

**Comment by drHyperion451** [comment]
Okay. I think I will do something like this: https://www.youtube.com/watch?v=hBYVxQLtrqQ

**Comment by MrTorfick** [comment]
> Okay. I think I will do something like this: https://www.youtube.com/watch?v=hBYVxQLtrqQ

Thanks for passing me that video, I will keep it in mind.

I will probably do the translation at the end of December, which is when I have free time.

Sorry for the delay in my reply, I have had some unforeseen events that have taken me a lot of time.
