### ISSUE TITLE
Site icons unreadable/not white on Firefox

### ISSUE THREAD

**Issue by moonlumen** [drHyperion451/does-uBO-bypass-yt#6]
**Firefox:**
![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/132274246/61478893-7287-4c2e-875e-2d8d1aa49914)
**Edge/Chromium:**
![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/132274246/50ee01e8-7fd5-4355-b49d-7fb51111f7c5)

I am not using any addons like dark reader or a firefox theme, but my OS' preferred theme is dark mode.

(edited by the owner:):

Os: Windows 11
Browser: Firefox v119.0 64 bit.

**Comment by drHyperion451** [comment]
What OS are you using?

**Comment by drHyperion451** [comment]
It's a bit weird because it works good for me in Firefox from MacOS. I will update this when I have time to test it to other browsers.

**Comment by linus-jansson** [comment]
Windows 11 works for me as well on firefox
![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/30862662/66a8f485-0b83-48aa-ba10-ad5b214b5725)

**Comment by moonlumen** [comment]
> What OS are you using?

Windows 11

**Comment by moonlumen** [comment]
Restarting my PC fixed this. I guess this was just some kind of a one time issue on my end..?

**Comment by Shivangbhatnagar237** [comment]
![image](https://github.com/drHyperion451/does-uBO-bypass-yt/assets/47966497/4657d972-da34-44c7-bece-1fd4346c40a5)

Is it supposed to do this?

**Comment by moonlumen** [comment]
I would make a separate issue for that

**Comment by drHyperion451** [comment]
@Shivangbhatnagar237 Please, do not necro closed issues if they are not the same problem as before. If you still have issues, please open another issue and follow the instructions. Thanks!
